# Generated by Django 6.0.1 on 2026-01-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('merge', 'Merge PDFs'), ('img2pdf', 'Image to PDF'), ('pdf2word', 'PDF to Word'), ('pdf2excel', 'PDF to Excel')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('original_filenames', models.TextField(help_text='Comma-separated list of original filenames')),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
